"""Blender: wrap the untouched canonical front photograph onto a real can mesh.
Blender -b --python 26_SOBAYA_BEER_RAIN/tool/build_cans.py
Provisional label PNGs are generated by build_labels.py first.
"""
import bpy,math,sys
lane = "--lane" in sys.argv
from pathlib import Path
root=Path(__file__).resolve().parents[2];out=root/'04_GAME_ASSETS/3d/props/beer_rain_cans';out.mkdir(parents=True,exist_ok=True)
for name in ['super_try','light','happoshu']:
 bpy.ops.wm.read_factory_settings(use_empty=True)
 imagepath=root/'03_SCRIPTS/00_TEMPLATES/props/product_super_try.png' if name=='super_try' else out/f'{name}.png'
 mat=bpy.data.materials.new('Printed aluminium');mat.use_nodes=True;bsdf=mat.node_tree.nodes.get('Principled BSDF');bsdf.inputs['Metallic'].default_value=.28;bsdf.inputs['Roughness'].default_value=.32
 tex=mat.node_tree.nodes.new('ShaderNodeTexImage');tex.image=bpy.data.images.load(str(imagepath));mat.node_tree.links.new(tex.outputs['Color'],bsdf.inputs['Base Color'])
 # Front orthographic projection of the canonical photograph, duplicated at back.
 n=64;verts=[];faces=[];profile=[(-.46,.22),(-.42,.25),(-.35,.28),(.32,.28),(.39,.245),(.44,.245)]
 for y,r in profile:
  for i in range(n):
   a=2*math.pi*i/n;verts.append((r*math.sin(a),-r*math.cos(a),y))
 for j in range(len(profile)-1):
  for i in range(n):faces.append((j*n+i,j*n+(i+1)%n,(j+1)*n+(i+1)%n,(j+1)*n+i))
 mesh=bpy.data.meshes.new('Can shell');mesh.from_pydata(verts,[],faces);mesh.update();uv=mesh.uv_layers.new()
 for poly in mesh.polygons:
  poly.use_smooth=True
  for li in poly.loop_indices:
   x,z,y=verts[mesh.loops[li].vertex_index]
   if name=='super_try':u=.5+x/.56*.49;v=.11+(y+.35)/.67*.73
   else:u=.5+x/.56*.96;v=.04+(y+.46)/.9*.92
   uv.data[li].uv=(u,min(.96,max(.04,v)))
 obj=bpy.data.objects.new(name,mesh);bpy.context.collection.objects.link(obj);obj.data.materials.append(mat)
 if lane:
  back=bpy.data.materials.new('Common unmarked back');back.use_nodes=True
  b=back.node_tree.nodes.get('Principled BSDF');b.inputs['Base Color'].default_value=(.65,.68,.7,1);b.inputs['Metallic'].default_value=.28;b.inputs['Roughness'].default_value=.32
  obj.data.materials.append(back)
  for poly in mesh.polygons:
   # Only a 140-degree front sector carries identifying printing.
   a=2*math.pi*((poly.index % n)+.5)/n
   if math.cos(a)<math.cos(math.radians(70)):poly.material_index=1

 metal=bpy.data.materials.new('Brushed silver');metal.diffuse_color=(.65,.68,.7,1);metal.use_nodes=True;mb=metal.node_tree.nodes.get('Principled BSDF');mb.inputs['Base Color'].default_value=(.65,.68,.7,1);mb.inputs['Metallic'].default_value=.85;mb.inputs['Roughness'].default_value=.24
 for y in [-.445,.445]:
  bpy.ops.mesh.primitive_cylinder_add(vertices=48,radius=.245,depth=.025,location=(0,0,y));bpy.context.object.data.materials.append(metal)
 bpy.ops.mesh.primitive_torus_add(major_radius=.23,minor_radius=.012,major_segments=48,minor_segments=8,location=(0,0,.463));bpy.context.object.data.materials.append(metal)
 bpy.ops.mesh.primitive_torus_add(major_radius=.058,minor_radius=.015,major_segments=24,minor_segments=8,location=(0,-.04,.471));bpy.context.object.scale.y=1.55;bpy.context.object.data.materials.append(metal)
 bpy.ops.export_scene.gltf(filepath=str(out/f'{name}{"_lane" if lane else ""}.glb'),export_format='GLB',export_animations=False)
