import React from 'react';
import {AbsoluteFill,Audio,Composition,Img,OffthreadVideo,Sequence,interpolate,registerRoot,staticFile,useCurrentFrame} from 'remotion';
import plan from './wan-edit-manifest.json';
const font='"Hiragino Kaku Gothic ProN","Hiragino Sans",sans-serif';
const Search=()=> <div style={{position:'absolute',right:48,bottom:36,width:380,height:48,display:'flex',alignItems:'center',gap:9,padding:4,background:'white',border:'1px solid #d8dee7',borderRadius:12,boxShadow:'0 3px 12px #0004',color:'#152238',fontSize:25,fontWeight:700}}><svg width="22" height="22" viewBox="0 0 24 24" style={{marginLeft:8}} fill="none" stroke="#66758a" strokeWidth="2"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg><span style={{flex:1,whiteSpace:'nowrap'}}>チュア　窓際族</span><span style={{height:38,padding:'3px 14px',background:'#173c72',color:'white',borderRadius:8,fontSize:23}}>検索</span></div>;
const Text=({text,sub}:{text:string,sub?:string})=><div style={{position:'absolute',left:48,top:42,color:'white',fontWeight:800,fontSize:42,lineHeight:1.5,letterSpacing:1,whiteSpace:'pre-line',textShadow:'0 2px 5px #000b,0 0 16px #0007'}}>{text}{sub&&<div style={{fontSize:27,marginTop:6}}>{sub}</div>}</div>;
const CM=({audioOverride}:{audioOverride?:string})=>{const f=useCurrentFrame();const replacementAudio=audioOverride||plan.replacementAudio;const current=plan.overlays.find(o=>f>=o.from&&f<o.to);const priceNew=f>=plan.priceSwitchFrame;return <AbsoluteFill style={{fontFamily:font,background:'#031124'}}>
<Sequence durationInFrames={plan.mainEndFrame}><OffthreadVideo muted={Boolean(replacementAudio)} src={staticFile(plan.inputVideo)} style={{width:1280,height:720,objectFit:'contain'}} volume={t=>interpolate(t,[plan.mainEndFrame-5,plan.mainEndFrame],[1,0],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})}/></Sequence>
{current&&current.id!=='offer'&&<Text text={current.text} sub={'sub'in current?current.sub:undefined}/>}
{current?.id==='offer'&&<><div style={{position:'absolute',left:36,top:30,fontSize:31,fontWeight:800,color:'#123154',textShadow:'0 1px 5px white'}}>週刊 窓際を作る</div><div style={{position:'absolute',left:38,bottom:111,fontSize:28,fontWeight:800,color:'#163655',background:'#fffffff0',padding:'9px 14px'}}>{current.text}</div><div style={{position:'absolute',right:32,top:205,width:425,height:270,textAlign:'center',color:'#16345c',background:'#fff',borderRadius:8,padding:'18px 0'}}>{!priceNew?<><div style={{fontSize:29}}>通常価格</div><div style={{fontSize:68,fontWeight:900}}>1,490<span style={{fontSize:33}}>円</span></div></>:<div style={{transform:`scale(${interpolate(f,[plan.priceSwitchFrame,plan.priceSwitchFrame+10],[.88,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})})`}}><div style={{fontSize:29,fontWeight:800}}>創刊号特別価格</div><div style={{fontSize:112,lineHeight:1.2,fontWeight:900,color:'#d71f24',letterSpacing:-6}}>399<span style={{fontSize:44,letterSpacing:0}}>円</span></div></div>}</div></>}
<Sequence from={plan.mainEndFrame}><AbsoluteFill><Img src={staticFile(plan.endingImage)} style={{width:'100%',height:'100%'}}/><div style={{position:'absolute',inset:0,display:'flex',justifyContent:'center',alignItems:'center',color:'white',fontSize:79,fontWeight:900,letterSpacing:3,textShadow:'0 3px 12px #001'}}>チュアゴスティーニ</div></AbsoluteFill></Sequence>
{replacementAudio ? <Audio src={staticFile(replacementAudio)}/> : <Sequence from={plan.endingAudioStartFrame}><Audio src={staticFile(plan.endingAudio)}/></Sequence>}
{f>=plan.searchStartFrame&&<Search/>}
</AbsoluteFill>};
registerRoot(()=> <><Composition id="ChuaWanCM" component={CM} width={1280} height={720} fps={30} durationInFrames={900}/><Composition id="ChuaFemaleCM" component={CM} defaultProps={{audioOverride:"narration_master_female_cm.wav"}} width={1280} height={720} fps={30} durationInFrames={900}/><Composition id="ChuaSobayaCM" component={CM} defaultProps={{audioOverride:"narration_master_sobaya_no_sokan.wav"}} width={1280} height={720} fps={30} durationInFrames={900}/></>);
