import React from 'react';
import {AbsoluteFill,Audio,Composition,Img,Sequence,interpolate,registerRoot,staticFile,useCurrentFrame} from 'remotion';
import plan from './edit-manifest.json';
const font='"Hiragino Kaku Gothic ProN","Hiragino Sans",sans-serif';
const Search=()=> <div style={{position:'absolute',right:48,bottom:36,width:380,height:48,display:'flex',alignItems:'center',gap:9,padding:4,background:'white',border:'1px solid #d8dee7',borderRadius:12,boxShadow:'0 3px 12px #0004',color:'#152238',fontSize:25,fontWeight:700}}><svg width="22" height="22" viewBox="0 0 24 24" style={{marginLeft:8}} fill="none" stroke="#66758a" strokeWidth="2"><circle cx="10" cy="10" r="6.5"/><path d="m15 15 6 6"/></svg><span style={{flex:1,whiteSpace:'nowrap'}}>チュア　窓際族</span><span style={{height:38,padding:'3px 14px',background:'#173c72',color:'white',borderRadius:8,fontSize:23}}>検索</span></div>;
const Text=({children,style={}}:{children:React.ReactNode,style?:React.CSSProperties})=><div style={{position:'absolute',left:48,top:48,color:'white',fontWeight:800,fontSize:44,lineHeight:1.5,letterSpacing:1,textShadow:'0 2px 5px #000b, 0 0 16px #0007',...style}}>{children}</div>;
const Scene=({i}:{i:number})=>{const f=useCurrentFrame();const s=plan.shots[i];const n=s.endFrame-s.startFrame;const scale=interpolate(f,[0,n],[1,1.035]);const closed=i===4&&f>35&&f<65;return <AbsoluteFill style={{overflow:'hidden'}}>
<div style={{position:'absolute',inset:0,transform:`scale(${i===4?1:scale})`}}><Img src={staticFile(s.output)} style={{width:'100%',height:'100%',objectFit:'cover'}}/>
{i===4&&closed&&<svg viewBox="0 0 1672 941" style={{position:'absolute',inset:0,width:'100%',height:'100%'}}><defs><linearGradient id="desk" x2="1" y2="1"><stop stopColor="#0b2849"/><stop offset="1" stopColor="#3975a9"/></linearGradient></defs><polygon points="179,113 499,183 518,444 196,470" fill="url(#desk)"/><path d="M270 210 Q400 160 470 350 Q350 320 210 430" fill="none" stroke="#66aada" strokeWidth="35" opacity=".35"/></svg>}
</div>
{ i<6&&<AbsoluteFill style={{background:'linear-gradient(180deg,rgba(0,0,0,.28),transparent 38%,transparent 68%,rgba(0,0,0,.45))'}}/>}
{i===0&&<Text style={{fontSize:49,top:58}}>あなたの部屋を、<br/>憧れの窓際に。</Text>}
{i===1&&<div style={{position:'absolute',right:50,top:95,color:'#fff',textShadow:'0 2px 7px #0009',textAlign:'right'}}><div style={{fontSize:29,fontWeight:700}}>週刊</div><div style={{fontSize:62,fontWeight:900,lineHeight:1.2}}>窓際を<br/>作る</div><div style={{fontSize:35,marginTop:22,fontWeight:700}}>創刊</div></div>}
{i===2&&<Text style={{fontSize:37,top:45}}>組み立てるたび、<br/>理想の窓際に近づいていく。</Text>}
{i===3&&<><Text style={{fontSize:43}}>{f<65?'アーロンチュア':'そば屋の仮面'}</Text><Text style={{top:112,fontSize:28}}>実物大で再現</Text>{f>=65&&<Text style={{top:590,fontSize:22}}>仮面は後続号に付属</Text>}</>}
{i===4&&<Text style={{fontSize:34,top:42,left:42}}>窓際族の日常を、リアルに体感。</Text>}
{i===5&&<Text style={{fontSize:38}}>窓際の楽しみ方も、<br/>詳しく解説。</Text>}
{i===6&&<><div style={{position:'absolute',left:35,top:27,fontSize:30,fontWeight:800,color:'#122f57'}}>週刊 窓際を作る</div><div style={{position:'absolute',left:40,bottom:110,fontSize:29,color:'#143355',fontWeight:800,background:'#ffffffe8',padding:'8px 14px'}}>アーロンチュアの材料一式付き</div><div style={{position:'absolute',right:40,top:215,width:355,textAlign:'center',color:'#16345c'}}>{s.startFrame+f<plan.graphics.priceSwitchFrame?<><div style={{fontSize:30}}>通常価格</div><div style={{fontSize:68,fontWeight:900}}>1,490<span style={{fontSize:34}}>円</span></div></>:<div style={{transform:`scale(${interpolate(f,[plan.graphics.priceSwitchFrame-s.startFrame,plan.graphics.priceSwitchFrame-s.startFrame+10],[.88,1],{extrapolateLeft:'clamp',extrapolateRight:'clamp'})})`}}><div style={{fontSize:30,fontWeight:800}}>創刊号特別価格</div><div style={{fontSize:112,lineHeight:1.2,fontWeight:900,color:'#d71f24',letterSpacing:-6}}>399<span style={{fontSize:44,letterSpacing:0}}>円</span></div></div>}</div></>}
{i===7&&<div style={{position:'absolute',inset:0,display:'flex',justifyContent:'center',alignItems:'center',color:'white',fontSize:79,fontWeight:900,letterSpacing:3,textShadow:'0 3px 12px #001'}}>チュアゴスティーニ</div>}
</AbsoluteFill>};
const CM=()=>{const f=useCurrentFrame();return <AbsoluteFill style={{fontFamily:font,background:'#031124'}}>{plan.shots.map((s,i)=><Sequence key={s.id} from={s.startFrame} durationInFrames={s.endFrame-s.startFrame}><Scene i={i}/>{'audio'in s&&s.audio&&<Sequence from={2}><Audio src={staticFile(s.audio)}/></Sequence>}</Sequence>)}<Sequence from={846}><Audio src={staticFile('ending_chuagostini_v3.wav')}/></Sequence>{f>=94&&<Search/>}</AbsoluteFill>};
registerRoot(()=> <Composition id="ChuaCM" component={CM} width={1280} height={720} fps={30} durationInFrames={900}/>);
