#!/bin/bash
set -eu
# Run from repository root. User-authorized Wan narrator repair.
IRODORI_TTS_CHECKPOINT=Aratako/Irodori-TTS-v4-Large IRODORI_CFG_SCALE_TEXT=5 IRODORI_DURATION_SCALE=1.0 tools/irodori_speak.sh 'あなたのへやを、あこがれのまどぎわに。' 03_SCRIPTS/chuagostini_20261003/wan_narration_repaired_01.wav 03_SCRIPTS/chuagostini_20261003/wan_narrator_repair_reference.wav 2026 '明瞭でテンポのよい、落ち着いた男性のCMナレーション。'
IRODORI_TTS_CHECKPOINT=Aratako/Irodori-TTS-v4-Large IRODORI_CFG_SCALE_TEXT=5 IRODORI_DURATION_SCALE=0.86 tools/irodori_speak.sh 'しゅうかん、まどぎわをつくる。そうかん。' 03_SCRIPTS/chuagostini_20261003/wan_narration_repaired_02.wav 03_SCRIPTS/chuagostini_20261003/wan_narrator_repair_reference.wav 2026 '明瞭でテンポのよい、落ち着いた男性のCMナレーション。'
IRODORI_TTS_CHECKPOINT=Aratako/Irodori-TTS-v4-Large IRODORI_CFG_SCALE_TEXT=5 IRODORI_DURATION_SCALE=1.0 tools/irodori_speak.sh '組み立てるたび、理想のまどぎわに近づいていく。' 03_SCRIPTS/chuagostini_20261003/wan_narration_repaired_03.wav 03_SCRIPTS/chuagostini_20261003/wan_narrator_repair_reference.wav 2027 '明瞭でテンポのよい、落ち着いた男性のCMナレーション。'
IRODORI_TTS_CHECKPOINT=Aratako/Irodori-TTS-v4-Large IRODORI_CFG_SCALE_TEXT=5 IRODORI_DURATION_SCALE=1.0 tools/irodori_speak.sh 'アーロンチュアから、そばやのかめんまで。じつぶつだいでさいげん。' 03_SCRIPTS/chuagostini_20261003/wan_narration_repaired_04.wav 03_SCRIPTS/chuagostini_20261003/wan_narrator_repair_reference.wav 2026 '明瞭でテンポのよい、落ち着いた男性のCMナレーション。'
IRODORI_TTS_CHECKPOINT=Aratako/Irodori-TTS-v4-Large IRODORI_CFG_SCALE_TEXT=5 IRODORI_DURATION_SCALE=1.0 tools/irodori_speak.sh 'まどぎわぞくのにちじょうを、リアルにたいかん。' 03_SCRIPTS/chuagostini_20261003/wan_narration_repaired_05.wav 03_SCRIPTS/chuagostini_20261003/wan_narrator_repair_reference.wav 2026 '明瞭でテンポのよい、落ち着いた男性のCMナレーション。'
IRODORI_TTS_CHECKPOINT=Aratako/Irodori-TTS-v4-Large IRODORI_CFG_SCALE_TEXT=5 IRODORI_DURATION_SCALE=1.0 tools/irodori_speak.sh 'まどぎわのたのしみかたも、くわしくかいせつ。' 03_SCRIPTS/chuagostini_20261003/wan_narration_repaired_06.wav 03_SCRIPTS/chuagostini_20261003/wan_narrator_repair_reference.wav 2026 '明瞭でテンポのよい、落ち着いた男性のCMナレーション。'
IRODORI_TTS_CHECKPOINT=Aratako/Irodori-TTS-v4-Large IRODORI_CFG_SCALE_TEXT=5 IRODORI_DURATION_SCALE=1.0 tools/irodori_speak.sh 'アーロンチュアのざいりょういっしきがついて、そうかんごうは、さんびゃくきゅうじゅうきゅうえん。' 03_SCRIPTS/chuagostini_20261003/wan_narration_repaired_07.wav 03_SCRIPTS/chuagostini_20261003/wan_narrator_repair_reference.wav 2026 '明瞭でテンポのよい、落ち着いた男性のCMナレーション。'
