import * as THREE from 'three';
import {GLTFLoader} from 'three/addons/loaders/GLTFLoader.js';
import {OrbitControls} from 'three/addons/controls/OrbitControls.js';
import {RoomEnvironment} from 'three/addons/environments/RoomEnvironment.js';
const $=id=>document.getElementById(id),stage=$('stage');
const renderer=new THREE.WebGLRenderer({antialias:true});renderer.setPixelRatio(Math.min(devicePixelRatio,2));renderer.setClearColor(0x26332c);renderer.toneMapping=THREE.ACESFilmicToneMapping;renderer.toneMappingExposure=.92;stage.prepend(renderer.domElement);
const scene=new THREE.Scene(),camera=new THREE.PerspectiveCamera(34,1,.01,100);const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.target.set(0,.88,0);
const pmrem=new THREE.PMREMGenerator(renderer);scene.environment=pmrem.fromScene(new RoomEnvironment(),.04).texture;pmrem.dispose();scene.environmentIntensity=.7;
scene.add(new THREE.HemisphereLight(0xe7f1eb,0x3e4941,.8));const key=new THREE.DirectionalLight(0xfff2e4,2.0);key.position.set(-3,4,5);scene.add(key);const fill=new THREE.DirectionalLight(0xcfddff,1.2);fill.position.set(3,2,-2);scene.add(fill);
const floor=new THREE.Mesh(new THREE.CircleGeometry(4,80),new THREE.MeshStandardMaterial({color:0x2d3e32,roughness:1}));floor.rotation.x=-Math.PI/2;floor.position.y=-.008;scene.add(floor);const grid=new THREE.GridHelper(5,25,0x54745a,0x364b3c);grid.position.y=-.007;scene.add(grid);
const names={Greeting:'挨拶 · 3秒',Idle:'待機',Walk:'歩行',Run:'走行',Aim:'拳銃を構える',AimShotgun:'散弾銃を構える',ReloadHandgun:'拳銃リロード',ReloadShotgun:'散弾銃リロード',Hit:'被弾',Evade:'回避',Kick:'キック',Climb:'梯子',Vault:'窓越え',Struggle:'もがく',BreakFree:'振りほどく',DanceStep:'ダンス 1',DanceDisco:'ダンス 2',DanceVictory:'ダンス 3',Test_HeadTurn:'検査 · 首振り',Test_ArmRaise:'検査 · 腕上げ 160°',Test_ElbowBend:'検査 · 肘曲げ',Test_KneeBend:'検査 · 膝曲げ',Rest:'初期姿勢'};
const base='/04_GAME_ASSETS/3d/characters/fukuchan/v2_20260913/';const files={v2:base+'fukuchan_v2.glb?rig=6',before:'/.local/fukuchan-v2-rig/before.glb',v1:'/04_GAME_ASSETS/3d/hazard_adopted/fukuchan.glb'};let actor,mixer,action,skeleton,clock=0,faceClock=0,duration=3,paused=false,faceView=false,detailView='',direction='front',loadId=0;
names.Test_Grip='検査 · 指を開く／握る';
const cache=new Map();const aimFrames=new Map();
const props=await new GLTFLoader().loadAsync('/04_GAME_ASSETS/3d/props/hazard_kit/items.glb');
const weapons={};for(const name of ['Handgun','Shotgun']){weapons[name]=props.scene.getObjectByName(name).clone();scene.add(weapons[name]);weapons[name].visible=false;}
function weapon(){for(const gun of Object.values(weapons))gun.visible=false;if(!actor||!$('weapon').checked||!/^Aim|^Reload/.test($('motion').value))return;actor.scene.updateMatrixWorld(true);const hand=actor.scene.getObjectByName('RightHand');const aim=aimFrames.get($('version').value);if(!hand||!aim)return;const q=hand.getWorldQuaternion(new THREE.Quaternion()).multiply(aim.clone().invert());const gun=weapons[$('motion').value.includes('Shotgun')?'Shotgun':'Handgun'];gun.visible=true;gun.position.copy(hand.getWorldPosition(new THREE.Vector3())).add(new THREE.Vector3(.025,.035,.065).applyQuaternion(q));gun.quaternion.copy(q);}

function resize(){const w=stage.clientWidth,h=stage.clientHeight;renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();}window.addEventListener('resize',resize);resize();
function view(){let target=new THREE.Vector3(0,faceView?1.57:.89,0),distance=faceView?.75:3.9;if(detailView==='upper'){target.set(0,1.28,0);distance=2.15;}if(detailView==='hands'&&actor){actor.scene.updateMatrixWorld(true);const hand=actor.scene.getObjectByName('RightHand');if(hand){hand.getWorldPosition(target);distance=.62;}}const d=direction==='side'?new THREE.Vector3(1,0,0):direction==='right'?new THREE.Vector3(-1,0,0):direction==='back'?new THREE.Vector3(0,0,-1):new THREE.Vector3(0,0,1);camera.position.copy(target).addScaledVector(d,distance);controls.target.copy(target);controls.update();}view();
function setMorph(name,value){actor?.scene.traverse(o=>{const i=o.morphTargetDictionary?.[name];if(i!==undefined)o.morphTargetInfluences[i]=value;});}
function setFace(){if($('version').value==='v1'){setMorph('SpeechOpen',0);setMorph('SpeechNarrow',0);return;}let blink=+$('blink').value,smile=+$('smile').value,mouth=+$('mouth').value;if($('auto-face').checked){const p=faceClock%3.7;blink=Math.max(0,1-Math.abs(p-2.1)/.11);if($('motion').value==='Greeting')smile=.5*Math.sin(Math.PI*Math.min(1,clock/duration))**2;}for(const [name,value] of [['Blink',blink],['Smile',smile],['SpeechOpen',mouth]])setMorph(name,value);}
function selectMotion(){if(!actor)return;mixer.stopAllAction();actor.scene.traverse(o=>{if(o.isSkinnedMesh)o.skeleton.pose();});const choice=$('motion').value;let id=choice;if($('version').value==='v1')id={Idle:'Adopted_Library_Idle_A',Walk:'Adopted_Library_Walk',Run:'Adopted_Candidate_Mixamo_Run'}[choice]??choice;const clip=actor.animations.find(c=>c.name===id);clock=0;duration=clip?.duration||3;action=clip?mixer.clipAction(clip).reset().play():null;sample();}
function sample(){if(!actor)return;mixer.setTime(clock);setFace();weapon();$('seek').value=clock/duration;$('time').textContent=clock.toFixed(2)+' / '+duration.toFixed(2)+' 秒';}
async function load(){const savedClock=clock;const id=++loadId,version=$('version').value;$('loading').hidden=false;try{if(!cache.has(version))cache.set(version,await new GLTFLoader().loadAsync(files[version]));if(id!==loadId)return;if(actor)scene.remove(actor.scene);if(skeleton)scene.remove(skeleton);actor=cache.get(version);scene.add(actor.scene);mixer=new THREE.AnimationMixer(actor.scene);const aimClip=actor.animations.find(c=>c.name==='Aim');if(aimClip){mixer.clipAction(aimClip).play();mixer.setTime(0);actor.scene.updateMatrixWorld(true);aimFrames.set(version,actor.scene.getObjectByName('RightHand').getWorldQuaternion(new THREE.Quaternion()));mixer.stopAllAction();}skeleton=new THREE.SkeletonHelper(actor.scene);skeleton.material.depthTest=false;skeleton.renderOrder=5;skeleton.visible=$('bones').checked;scene.add(skeleton);const old=$('motion').value;$('motion').replaceChildren();for(const [key,label] of Object.entries(names)){if(key==='Rest'||actor.animations.some(c=>c.name===key)||version==='v1'&&['Idle','Walk','Run'].includes(key)){const o=document.createElement('option');o.value=key;o.textContent=label;$('motion').append(o);}}$('motion').value=[...$('motion').options].some(o=>o.value===old)?old:(version==='v2'?'Greeting':'Idle');$('face-controls').classList.toggle('disabled',version==='v1');$('hair').disabled=version==='v1';$('download').href=files[version];let triangles=0,bones=new Set(),meshes=0;actor.scene.traverse(o=>{if(o.isMesh){meshes++;triangles+=(o.geometry.index?.count??o.geometry.attributes.position.count)/3;}if(o.isBone)bones.add(o.uuid);});$('status').textContent=triangles.toLocaleString()+' 三角面 · '+bones.size+' ボーン\n'+actor.animations.length+' 動作 · '+meshes+' メッシュ';selectMotion();clock=Math.min(savedClock,duration);sample();display();$('loading').hidden=true;}catch(e){$('loading').textContent='読み込みに失敗しました: '+e.message;throw e;}}
function display(){const hair=actor?.scene.getObjectByName('Hair');if(hair)hair.visible=$('hair').checked;skeleton&&(skeleton.visible=$('bones').checked);actor?.scene.traverse(o=>{if(o.isMesh){for(const m of(Array.isArray(o.material)?o.material:[o.material]))m.wireframe=$('wire').checked;}});}
$('weapon').onchange=weapon;$('auto-face').onchange=setFace;$('version').onchange=load;$('motion').onchange=selectMotion;$('play').onclick=()=>{paused=!paused;$('play').textContent=paused?'再生':'一時停止';};$('seek').oninput=()=>{paused=true;$('play').textContent='再生';clock=+$('seek').value*duration;sample();};
for(const id of ['blink','smile','mouth'])$(id).oninput=()=>{$('auto-face').checked=false;$(id+'-value').textContent=Math.round(+$(id).value*100)+'%';setFace();};for(const id of ['hair','bones','wire'])$(id).onchange=display;
for(const b of document.querySelectorAll('[data-view]'))b.onclick=()=>{direction=b.dataset.view;view();};$('full').onclick=()=>{faceView=false;detailView='';view();};$('face').onclick=()=>{faceView=true;detailView='';view();};
$('upper').onclick=()=>{detailView='upper';faceView=false;view();};$('hands').onclick=()=>{detailView='hands';faceView=false;view();};
let last=performance.now();renderer.setAnimationLoop(now=>{const dt=Math.min((now-last)/1000,.1);last=now;if(!paused){faceClock+=dt*+$('speed').value;clock=(clock+dt*+$('speed').value)%duration;sample();}controls.update();renderer.render(scene,camera);});await load();
